#!/bin/sh

# This is an example script that gets called just after pointird performed a calibration.
# pointird will not proceed as long as this script is running.

# Here, we are going to control a servo motor to insert an IR-filter attached to its shaft using ServUSB.
# (https://github.com/zwostein/ServUSB)
# This script will enable the servo and move the shaft into some position to insert the filter.
# It will wait a second for the servo to finish its movement and then disables the servo again. (so the servo can be moved by hand)

echo -n "Inserting IR pass filter ... "
/usr/local/bin/servusb -e 255 || exit 1
sleep 1
/usr/local/bin/servusb -d || exit 1
echo "done"
